---
# SSH登录用户名称
username: root
# SSH登录用户密码
passwd: 'Password1qaz'
# SSH需要登录的IP地址列表
ips:
- 120.24.173.49
# SSH登录后需要执行的命令
execs:
- mkdir code
- cd code; git clone https://github.com/pangff/cloudAuto.git
- cd code/cloudAuto/config; chmod 777 command.sh; ./command.sh
